services:
  postgres:
    container_name: postgres
    image: postgres:16.4-alpine
    restart: unless-stopped
    volumes:
      - ./.docker_volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    container_name: django
    build: ./backend
    command: gunicorn --bind=0.0.0.0:8000 --workers=3 --max-requests=1000 --reload config.wsgi:application
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
